### ISSUE TITLE
`this.workspace.openProject is not a function` error after upgrading to v13.2.0 (was working in v13.1.3)

### ISSUE THREAD

**Issue by micke-dahlgren** [acacode/swagger-typescript-api#1290]
After upgrading from **13.1.3** to **13.2.0**, running the generator throws:
**_ERROR this.workspace.openProject is not a function_**

script that triggers it:
` npx swagger-typescript-api@13.2.0 generate  -p .../swagger.json -o ./src/models/apiModels -n ...\WebServiceApiModels.ts --no-client.`
