### ISSUE TITLE
Getting this.workspace.openProject is not a function when generating

### ISSUE THREAD

**Issue by Gaspa79** [acacode/swagger-typescript-api#1285]
Hey! I noticed that since updating node (LTS version v22.16.0) I've been getting 

```
this.workspace.openProject is not a function 
```

Whenever i run a regular generate. I'm doing the exact same thing as usual and can't find any workarounds for this. Any ideas? Thanks!

Stacktrace here:

```
at Biome.openProject (node_modules\@biomejs\js-api\dist\index.js:59:31)
    at Biome.create (node_modules\@biomejs\js-api\dist\index.js:21:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async CodeFormatter.format (/C:/Repos/SJ/SoyJurista-Ng/node_modules/swagger-typescript-api/dist/src-CyhiKzh-.js:41:17)
    at async CodeFormatter.formatCode (/C:/Repos/SJ/SoyJurista-Ng/node_modules/swagger-typescript-api/dist/src-CyhiKzh-.js:55:22)
    at async CodeGenProcess.createOutputFileInfo (/C:/Repos/SJ/SoyJurista-Ng/node_modules/swagger-typescript-api/dist/src-CyhiKzh-.js:2963:17)
    at async CodeGenProcess.createSingleFileInfo (/C:/Repos/SJ/SoyJurista-Ng/node_modules/swagger-typescript-api/dist/src-CyhiKzh-.js:2933:10)
    at async CodeGenProcess.generateOutputFiles (/C:/Repos/SJ/SoyJurista-Ng/node_modules/swagger-typescript-api/dist/src-CyhiKzh-.js:2882:99)
    at async CodeGenProcess.start (/C:/Repos/SJ/SoyJurista-Ng/node_modules/swagger-typescript-api/dist/src-CyhiKzh-.js:2791:19)
    at async generateApi (/C:/Repos/SJ/SoyJurista-Ng/node_modules/swagger-typescript-api/dist/src-CyhiKzh-.js:3129:9)
```

**Comment by Hassenamri005** [comment]
i have the same issue

**Comment by Arclipsed** [comment]
Switching to version: swagger-typescript-api@13.0.28 Fixed it for me

**Comment by Gian-Marco-27** [comment]
same 

`this.workspace.openProject is not a function`

**Comment by TheRichCookie** [comment]
same here getting this error

**Comment by smorimoto** [comment]
Could you try the latest version? If that doesn't fix the issue, we will try to downgrade the internal Biome.

**Comment by smorimoto** [comment]
Have you tried 13.2.2?

**Comment by AsGamer1** [comment]
> Have you tried 13.2.2?

@smorimoto I just installed 13.2.2 and it gives me the same error.

**Comment by paulstelzer** [comment]
Also getting the same error with 13.2.2

ℹ start generating your typescript api                                                                                                                                                      8:50:37 PM

 ERROR  this.workspace.openProject is not a function                                                                                                                                         8:50:38 PM

    at Biome.openProject (node_modules/@biomejs/js-api/dist/index.js:59:31)
    at Biome.create (node_modules/@biomejs/js-api/dist/index.js:21:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async CodeFormatter.format (node_modules/swagger-typescript-api/dist/src-CuoIgJ3d.js:41:17)
    at async CodeFormatter.formatCode (node_modules/swagger-typescript-api/dist/src-CuoIgJ3d.js:55:22)
    at async CodeGenProcess.createOutputFileInfo (node_modules/swagger-typescript-api/dist/src-CuoIgJ3d.js:2963:17)
    at async CodeGenProcess.createSingleFileInfo (node_modules/swagger-typescript-api/dist/src-CuoIgJ3d.js:2933:10)
    at async CodeGenProcess.generateOutputFiles (node_modules/swagger-typescript-api/dist/src-CuoIgJ3d.js:2882:99)
    at async CodeGenProcess.start (node_modules/swagger-typescript-api/dist/src-CuoIgJ3d.js:2791:19)
    at async generateApi (node_modules/swagger-typescript-api/dist/src-CuoIgJ3d.js:3129:9)

**Comment by micke-dahlgren** [comment]
for me it works on any version < 13.2.0

**Comment by smorimoto** [comment]
Can you try [13.2.3](https://www.npmjs.com/package/swagger-typescript-api/v/13.2.3)?

**Comment by Sagie501** [comment]
> Can you try [13.2.3](https://www.npmjs.com/package/swagger-typescript-api/v/13.2.3)?

For me it didn't work with 13.2.2, but with 13.2.3 it works so it seems that this issue is solved 🙂

**Comment by smorimoto** [comment]
Apparently, there was something wrong with the dependency resolution in npm. In fact, there was no problem with other package managers.
