### ISSUE TITLE
TSError: ⨯ Unable to compile TypeScript: cypress/components/api/swagger/generate_api_client.ts:22:29 - error TS2339: Property 'name' does not exist on type 'FileInfo'.

### ISSUE THREAD

**Issue by firmanserdana** [acacode/swagger-typescript-api#576]
After upgrading into 13.0.2 from 12.x.x this error happening

Case is, in my place, we will generate api clients for cypress test
