### ISSUE TITLE
type: module & moduleResolution: NodeNext fails if the Typescript dependency version is 4.7+

### ISSUE THREAD

**Issue by ClementValot** [acacode/swagger-typescript-api#370]
Node version: 16.15.0
OS: Windows 

Code to reproduce: 
package.json
```
{
  "name": "swagger-typescript-api-bug",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "main": "index.js",
  "scripts": {
    "fetch-types": "swagger-typescript-api -p https://my-website-api.com"
  },
  "license": "ISC",
  "dependencies": {
    "swagger-typescript-api": "^9.3.1"
  }
}
```

tsconfig.json
```
{
  "include": ["./src/**/*"],
  "exclude": [],
  "compilerOptions": {
    "esModuleInterop": true,
    "module": "ES6",
    "moduleResolution": "NodeNext",
    "target": "ES6"
  },
   "ts-node": {
      "transpileOnly": true
    }
}
```

running the `fetch-types` script raises the following stack: 
``` 
TypeError: host.fileExists is not a function
    at getPackageJsonInfo (D:\Projects\WebstormProjects\testing-tools\node_modules\typescript\lib\typescript.js:43798:37)
    at Object.getPackageScopeForPath (D:\Projects\WebstormProjects\testing-tools\node_modules\typescript\lib\typescript.js:43765:23)
    at lookupFromPackageJson (D:\Projects\WebstormProjects\testing-tools\node_modules\typescript\lib\typescript.js:116488:28)
    at Object.getImpliedNodeFormatForFile (D:\Projects\WebstormProjects\testing-tools\node_modules\typescript\lib\typescript.js:116482:200)
    at acquireOrUpdateDocument (D:\Projects\WebstormProjects\testing-tools\node_modules\typescript\lib\typescript.js:136051:47)
    at Object.acquireDocumentWithKey (D:\Projects\WebstormProjects\testing-tools\node_modules\typescript\lib\typescript.js:136026:20)
    at getOrCreateSourceFileByPath (D:\Projects\WebstormProjects\testing-tools\node_modules\typescript\lib\typescript.js:165211:41)
    at Object.getOrCreateSourceFile [as getSourceFile] (D:\Projects\WebstormProjects\testing-tools\node_modules\typescript\lib\typescript.js:165158:24) 
    at findSourceFileWorker (D:\Projects\WebstormProjects\testing-tools\node_modules\typescript\lib\typescript.js:118298:29)
    at findSourceFile (D:\Projects\WebstormProjects\testing-tools\node_modules\typescript\lib\typescript.js:118196:26)
error Command failed with exit code 1.
```
No error is raised if the dependency is Typescript 4.6.2

**Comment by js2me** [comment]
Hello @ClementValot can you reproduce this problem with using swagger-typescript-api `10.0.1`?

**Comment by ClementValot** [comment]
Same issue with the minimal configuration above. Works with `moduleResolution=Node` but fails with `moduleResolution=NodeNext` or `Node16`

**Comment by js2me** [comment]
@ClementValot thanks, will work

**Comment by cipchk** [comment]
@js2me Any progress?

**Comment by wingkwong** [comment]
Also had the same error.

**Comment by AlexeyBee** [comment]
Any progress?

**Comment by nksfrank** [comment]
same error

```JSON
{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "ES2020",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "allowSyntheticDefaultImports": true,
    "typeRoots": ["types", "./node_modules/@types"],
    "useUnknownInCatchVariables": true
  }
}
```

```
{
  "scripts": {
    "generate-api": "swagger-typescript-api -r --unwrap-response-data --single-http-client --modular --module-name-index=1 -p http://localhost:5000/swagger/v1/swagger.json -o ./packages/queries/src/api"
  },
  "devDependencies": {
    "swagger-typescript-api": "^10.0.1",
    "typescript": "^4.8.2"
  }
}
```

```
TypeError: host.fileExists is not a function
    at Object.fileExists (C:\src\Bygghemma.ECP.Web\Clients\node_modules\typescript\lib\typescript.js:167586:63)
    at host.fileExists (C:\src\Bygghemma.ECP.Web\Clients\node_modules\typescript\lib\typescript.js:117448:47)
    at tryFileLookup (C:\src\Bygghemma.ECP.Web\Clients\node_modules\typescript\lib\typescript.js:44293:28)
    at tryFile (C:\src\Bygghemma.ECP.Web\Clients\node_modules\typescript\lib\typescript.js:44285:20)
    at tryExtension (C:\src\Bygghemma.ECP.Web\Clients\node_modules\typescript\lib\typescript.js:44277:24)
    at tryAddingExtensions (C:\src\Bygghemma.ECP.Web\Clients\node_modules\typescript\lib\typescript.js:44255:32)
    at loadModuleFromFile (C:\src\Bygghemma.ECP.Web\Clients\node_modules\typescript\lib\typescript.js:44188:45)
    at nodeLoadModuleByRelativeName (C:\src\Bygghemma.ECP.Web\Clients\node_modules\typescript\lib\typescript.js:44112:36)
    at tryResolve (C:\src\Bygghemma.ECP.Web\Clients\node_modules\typescript\lib\typescript.js:44069:34)
    at C:\src\Bygghemma.ECP.Web\Clients\node_modules\typescript\lib\typescript.js:44032:69
error Command failed with exit code 1.```

**Comment by treet** [comment]
Same issue, after a lot of testing it seems that swagger-typescript-api simply does not work with typescript 4.8.2 (released 16 hours ago). When locking typescript to `4.7.4` (using e.g. yarn resolutions) it works. 

Since swagger-typescript-api requests `"typescript: "^4.7.4"` it will automatically pick up typescript 4.8.2, so unless you got an existing lockfile that resolves typescript ^4.7.4 to 4.7.4 (the no longer latest version) swagger-typescript-api won't run.

**Comment by jiameiw** [comment]
same error with typescript^4.7.4  ts-node 10.0.0
have you found the cause yet And when will it be solved，thx a lot

**Comment by danielmackay** [comment]
Hey guys, I've run into this also.  Any ETA?

**Comment by vanslly** [comment]
If you use yarn you can workaround this issue by using yarn resolutions in your `package.json`.

`swagger-typescript-api@^10.0.1` has a dependency of `typescript@^4.7.4` which resolves to `typescript@4.8.2` for me, which causes this error.

Adding a resolution of `"typescript": "4.7.4"` ensures the breaking version of TypeScript isn't used.
![image](https://user-images.githubusercontent.com/2443418/187118079-ffe7f47e-e27c-4960-b229-33b0a8fe7e0e.png)

**Comment by VitaliKhileuski** [comment]
same problem

**Comment by fabsenet** [comment]
or, if you do not have any idea about fancy package resolutions, you just edit the typescript version, you depend on yourself. that would be line 119 in the screenshot 🤷‍♂️

**Comment by tiborgg** [comment]
Having the same issue. @vanslly's solution fixes the issue for me. Thanks!

**Comment by shreypdev** [comment]
I am still having issue after adding resolution, can you tell me exactly what you did @tiborgg please

**Comment by shreypdev** [comment]
Actually sorry got it working thanks everyone for help

**Comment by vanslly** [comment]
For those using NPM, which lacks package resolution overrides like yarn, you may "pin" the version of your own `typescript` dependency as @fabsenet said above.

In my case I could have just changed `typescript@^4.1.2` to `typescript@4.1.2`, so removing the caret symbol. However, the `package.json` of `swagger-typescript-api` specifies a minimum compatible version of `typescript@4.7.4`, so I do this at my own risk. I could also pin to `typescript@4.7.4` and do an application-wide upgrade.

The next version will pin the TypeScript version to `4.7.X` with #401.

**Comment by trevorwhealy** [comment]
We're having the same problem. Thanks to @treet who explained this very well - 
> Since swagger-typescript-api requests "typescript: "^4.7.4" it will automatically pick up typescript 4.8.2
> (and...) swagger-typescript-api simply does not work with typescript 4.8.2

This means that people interacting with this generator via `npx` like so:

```
npx swagger-typescript-api -p http://localhost:3001/swagger-json
```

Are not going to be able to escape the error by going back to an earlier version of this library
```
npx swagger-typescript-api@9.3.1 -p http://localhost:3001/swagger-json
```

Because both `9.3.1` and the latest release `10.0.1` will pull in typescript `4.8.2` due to the typescript package.json dependency being `^4.7.4` in both versions.

**Comment by trevorwhealy** [comment]
We're having the same problem. Thanks to @treet who explained this very well - 
> Since swagger-typescript-api requests "typescript: "^4.7.4" it will automatically pick up typescript 4.8.2
> (and...) swagger-typescript-api simply does not work with typescript 4.8.2

This means that people interacting with this generator via `npx` like so:

```
npx swagger-typescript-api -p http://localhost:3001/swagger-json
```

Are not going to be able to escape the error by going back to an earlier version of this library
```
npx swagger-typescript-api@9.3.1 -p http://localhost:3001/swagger-json
```

Because, both `9.3.1` and the latest release `10.0.1` pull in typescript `4.8.2` due to the typescript package.json dependency using the minor version bump requirement`^4.x` in both versions. 

So even though it was [recently bumped from 4.2.4 to 4.7.4 in the latest 10.0 release](
https://github.com/acacode/swagger-typescript-api/pull/294/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519), both will still pull in 4.8.2.

It seems that this library swapped to using typescript `^4.x` as far back as the [2.0 release](https://github.com/acacode/swagger-typescript-api/pull/86/files)

**Comment by matsgm** [comment]
> For those using NPM, which lacks package resolution overrides like yarn, you may "pin" the version of your own `typescript` dependency as @fabsenet said above.
> 
> In my case I could have just changed `typescript@^4.1.2` to `typescript@4.1.2`, so removing the caret symbol. So by running `npm i -D typescript@4.1.2`. However, the `package.json` of `swagger-typescript-api` specifies a minimum compatible version of `typescript@4.7.4`, so I do this at my own risk. I could also pin to `typescript@4.7.4` and do an application-wide upgrade.
> 
> The next version will pin the TypeScript version to `4.7.X` with #401.

This solution, which only overrides swagger-typescript-api, works for me using npm:

```
  "overrides": {
    "swagger-typescript-api": {
      "typescript": "4.7.4"
    }
  }
  ```

**Comment by danielmackay** [comment]
> > For those using NPM, which lacks package resolution overrides like yarn, you may "pin" the version of your own `typescript` dependency as @fabsenet said above.
> > In my case I could have just changed `typescript@^4.1.2` to `typescript@4.1.2`, so removing the caret symbol. So by running `npm i -D typescript@4.1.2`. However, the `package.json` of `swagger-typescript-api` specifies a minimum compatible version of `typescript@4.7.4`, so I do this at my own risk. I could also pin to `typescript@4.7.4` and do an application-wide upgrade.
> > The next version will pin the TypeScript version to `4.7.X` with #401.
> 
> This solution, which only overrides swagger-typescript-api, works for me using npm:
> 
> ```
>   package.json
>   
>   "overrides": {
>     "swagger-typescript-api": {
>       "typescript": "4.7.4"
>     }
>   }
> ```

This worked for me.  Thanks @matsgm!

**Comment by juanmait** [comment]
> For those using NPM, which lacks package resolution overrides like yarn, you may "pin" the version of your own `typescript` dependency as @fabsenet said above.
> 
> In my case I could have just changed `typescript@^4.1.2` to `typescript@4.1.2`, so removing the caret symbol. So by running `npm i -D typescript@4.1.2`. However, the `package.json` of `swagger-typescript-api` specifies a minimum compatible version of `typescript@4.7.4`, so I do this at my own risk. I could also pin to `typescript@4.7.4` and do an application-wide upgrade.
> 
> The next version will pin the TypeScript version to `4.7.X` with #401.

Worked for me although I'm using `pnpm` and I had to delete and regenerate the `pnpm-lock.yaml` file for some reason.

**Comment by progdesigner** [comment]
src/formatFileContent.js

class LanguageServiceHost {
...
  fileExists(file) {
    return ts.sys.fileExists(file);
  }
...

Thank you for adding the above.

**Comment by csi-lk** [comment]
I couldn't get the resolution stuff to work in yarn berry, so used @jnig's PR linked above until merged

```
"swagger-typescript-api": "github:jnig/swagger-typescript-api.git#8fba36a790fae21ef073154dab2c9da79908de17",
```

**Comment by XantreGodlike** [comment]
Helps with yarn
```json
"resolutions": {
	"swagger-typescript-api/**/typescript": "4.7.4"
}
```

**Comment by Jungzl** [comment]
For anyone who are using pnpm
```json
  "pnpm": {
    "overrides": {
      "swagger-typescript-api>typescript": "4.7.4"
    }
  }
```

**Comment by vanslly** [comment]
> how correct use "overrides" for npm? I added this in my package.json but it's not work(

@Misinin make sure to be using npm@8.3 or higher: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

```JSON
{
  "overrides": {
    "swagger-typescript-api": {
      "typescript": "4.7.4"
    }
  }
}
```

**Comment by Misinin** [comment]
@vanslly Thank you so much that helped me!

**Comment by AndreiSoroka** [comment]
Fixed in typescript@^4.8.4

**Comment by emlyn-arkahna** [comment]
Anyone else still seeing an issue after updating to 10.0.3 or should I raise a new bug?

**Comment by js2me** [comment]
Hi guys, maybe better to move the typescript dependency to peerDependencies of this project and set versions range?

**Comment by NikYushchenko** [comment]
> 

I don't have an error after updating to 10.0.3 version

**Comment by vanslly** [comment]
Issue has been resolved since version `10.0.2`. @ClementValot would you like to close the issue?

**Comment by ClementValot** [comment]
Indeed, thanks for the heads-up :)
